# Generated by Django 3.1.3 on 2021-02-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstockmsg',
            name='stockName',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
