# Generated by Django 3.1.3 on 2021-02-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_getstockmsg_stockname'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstockmsg',
            name='querySuccess',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
