# Generated by Django 3.1.3 on 2021-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0003_getstockmsg_querysuccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getstockmsg',
            name='querySuccess',
            field=models.BooleanField(default=False),
        ),
    ]
